<?php
module_load_include('inc', 'pets_owners_storage', 'includes/validation_rules/custom_fapi_validation_rules');
module_load_include('inc', 'pets_owners_storage', 'includes/db/db');
module_load_include('inc', 'pets_owners_storage', 'includes/pets_owners_storage.forms');
/**
 * Implement hook_menu().
 */
function pets_owners_storage_menu() {
  $items = array();

  $items['pets_owners_storage/pets_owners_form'] = array(
    'title' => 'Pets owners form',
    'description' => 'A new pet owners form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pets_owners_storage_form'),
    'access arguments' => array('access pets owners form'),
  );

  $items['pets_owners_storage/pets_owners_page'] = array(
    'title' => 'Pets owners',
    'description' => 'All pets owners in DB',
    'page callback' => 'pets_owners_storage_admin_page',
    'access arguments' => array('access all pets owners table'),
    'file' => 'includes/pets_owners_storage.pages.inc',
  );

  $items['pets_owners_storage/edit_form/%'] = array(
    'title' => 'Edit pets owner',
    'description' => 'Pets owners edit form',
    'page callback' => 'pets_owners_storage_edit_form_callback',
    'page arguments' => array(2),
    'access arguments' => array('access all pets owners table'),
    'file' => 'includes/pets_owners_storage.pages.inc',
  );

  $items['pets_owners_storage/delete_owner/%'] = array(
    'page callback' => 'pets_owners_storage_delete_callback',
    'page arguments' => array(2),
    'access arguments' => array('access all pets owners table'),
    'file' => 'includes/pets_owners_storage.pages.inc',
  );

  $items['pets_owners_storage/confirm_delete/%'] = array(
    'page callback' => 'pets_owners_storage_confirm_callback',
    'page arguments' => array(2),
    'access arguments' => array('access all pets owners table'),
    'file' => 'includes/pets_owners_storage.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function pets_owners_storage_permission() {
  return array(
    'access pets owners form' => array(
      'title' => t('Access form for adding new pets owner in pets_owners_storage module.'),
    ),
    'access all pets owners table' => array(
      'title' => t('Access table of all pets owners in pets_owners_storage module.'),
    ),
  );
}
