<?php

module_load_include('inc', 'd7', 'includes/custom_fapi_validation_rules');
/**
 * Implement hook_menu().
 */
function d7_menu() {
  $items = array();

  $items['d7/d7form'] = array( //this creates a URL that will call this form at "d7/d7form"
    'title' => 'News subscription',
    'description' => 'A form to mess around with.',
    'page callback' => 'd7_subscription_callback',
    'page arguments' => array('d7_subscription_form'),
    'access arguments' => array('access d7 content'),
  );

  return $items;
}

/**
 * Custom sub.
 */
function d7_subscription_form($form, &$form_state) {

  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#default_value' => t('Your name'),
    '#size' => 20,
    '#maxlength' => 20,
    '#required' => TRUE,
    '#rules' => array(
      'alpha_space',
      array(
        'rule' => 'length[1,20]',
        'error' => t('Please, enter a shorter than 20 char name.')
      )
    ),
  );

  $form['email'] = array(
    '#title' => t('E-mail'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#rules' => array(
      array(
        'rule' => 'email',
        'error' => t('Please, enter a valid email at %field.')
      ),
      array(
        'rule' => 'length[3,30]',
        'error' => t('Please, enter a shorter than 30 char email.')
      )
    ),
  );

  $form['agree'] = array(
    '#title' => t('I agree with all this stuff.'),
    '#type' => 'checkbox',
    '#default_value' => FALSE,
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit!'),
  );

  return $form;
}

/**
 * Implement hook_form_submit().
 */
function d7_subscription_form_submit($form, &$form_state) {

  drupal_set_message(t('Hello!'));
}

/**
 * Implements hook_permission().
 */
function d7_permission() {
  return array(
    'access d7 content' => array(
      'title' => t('Access content for the D7 module'),
    )
  );
}

/**
 * Custom callback function
 * @param $form
 * @return array|mixed
 */
function d7_subscription_callback($form) {
  return drupal_get_form($form);
}



