<?php

module_load_include('inc', 'batch_for_pets', 'includes/batch_for_pets.forms');
module_load_include('inc', 'batch_for_pets', 'includes/validation_rules/custom_fapi_validation_rules');

/**
 * Implement hook_menu().
 */
function batch_for_pets_menu() {
  $items = array();

  $items['batch_for_pets/batch_for_pets_change_name_form'] = array(
    'title' => 'Change names form',
    'description' => 'Change names form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('batch_for_pets_change_name_form'),
    'access arguments' => array('batch_for_pets access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function batch_for_pets_permission() {
  return array(
    'batch_for_pets access content' => array(
      'title' => t('Access form for changing name of pets owner in pets_owners_storage module.'),
    ),
  );
}






