<?php

/**
 * Implement hook_menu().
 */
function new_batch_menu() {
  $items = array();

  $items['change_name_form'] = array(
    'title' => 'Change name form',
    'description' => 'Form for changing pets owners names',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('new_batch_change_name_form'),
    'access arguments' => array('access form content'),
    'file' => '/includes/new_batch.forms.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function new_batch_permission() {
  return array(
    'access form content' => array(
      'title' => t('Access content for the New Batch module'),
    )
  );
}


/*
* Implements hook_cron().
*/
function new_batch_cron() {
  $result = db_query('SELECT title,nid FROM {node}');
$queue = DrupalQueue::get('change_titles');
foreach ($result as $title_node) {
  $queue->createItem($title_node);
}
}

/*
* Implements hook_cron_queue_info().
*/
function new_batch_cron_queue_info() {
  $queues['change_titles'] = array(
    'worker callback' => 'change_title',
    'time' => 120,
  );
  return $queues;
}

function change_title($data) {
  $result = db_update('node')
    ->fields(array('title' => str_replace('hicron', '', $data->title)))
//    ->fields(array(title => $data->title . 'hicron'))
    ->condition('nid', $data->nid)
    ->execute();
}



